apiVersion: v1
kind: Service
metadata:
  name: coord-service
spec:
  clusterIP: None
  selector:
    app: coord-node
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coord-node
spec:
  serviceName: "coord-service"
  replicas: 3
  selector:
    matchLabels:
      app: coord-node
  template:
    metadata:
      labels:
        app: coord-node
    spec:
      containers:
      - name: python-node
        image: algoritmos-coordenacao:v7
        imagePullPolicy: Never
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: APP_NAME
          value: "coord-node"
        - name: SERVICE_NAME
          value: "coord-service"
        - name: TOTAL_PROCESSOS
          value: "3"
        ports:
        - containerPort: 5000
